\documentclass{article}
\usepackage[margin=1em,paperheight=8cm,paperwidth=12cm]{geometry}  
\usepackage{booktabs,lipsum}
\begin{document}
<<echo=F,message=F,warning=F,comment="">>=
library(xtable)
library(stargazer)
library(kableExtra) 
library(Hmisc) 
data("mtcars")  # some example data 
df <-mtcars[1:3, 1:6]
@

<<echo=F,results="asis">>=
print(xtable(df,caption="Example with \\texttt{xtable}"), 
booktabs=T, caption.placement="top")
stargazer(df, summary=F, 
title="Example with \\texttt{stargazer}")
kable(df, booktabs = T, 
caption = "Example with  \\texttt{kable}  and \\texttt{kableExtra}")
latex(df, file = '', caption="Example with  \\texttt{Hmisc}")
@
\end{document}